version: '2'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.7
    volumes_from:
      - storage
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  go:
    image: h3poteto/golang
    env_file: .docker-env
    volumes:
      - .:/go/src/github.com/h3poteto/hanazawabot
    links:
      - mysql:mysql
    working_dir: /go/src/github.com/h3poteto/hanazawabot
    command: /bin/sh
