version: '2'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.7
    volumes_from:
      - storage
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  go:
    build: ./dockerfiles/development
    env_file: .docker-env
    volumes:
      - .:/root/app
    links:
      - mysql:mysql
    command: /bin/sh
