version: '2'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.7
    volumes_from:
      - storage
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  go:
    image: h3poteto/golang:1.9.4
    environment:
      HANAZAWA_DB_USER: root
      HANAZAWA_DB_HOST: mysql
      HANAZAWA_DB_PORT: 3306
      DEVELOPER_KEY: $DEVELOPER_KEY
      TWITTER_CONSUMER_KEY: $TWITTER_CONSUMER_KEY
      TWITTER_CONSUMER_SECRET: $TWITTER_CONSUMER_SECRET
      TWITTER_OAUTH_TOKEN: $TWITTER_OAUTH_TOKEN
      TWITTER_OAUTH_SECRET: $TWITTER_OAUTH_SECRET
      SLACK_URL: $SLACK_URL
    volumes:
      - .:/go/src/github.com/h3poteto/hanazawabot
    links:
      - mysql:mysql
    working_dir: /go/src/github.com/h3poteto/hanazawabot
    command: /bin/sh
