version: 2
jobs:
  build:
    docker:
      - image: h3poteto/golang
    working_directory: /go/src/github.com/h3poteto/hanazawabot
    steps:
      - checkout
      - run:
          name: Check golang version
          command: go version
      - restore_cache:
          name: Restoring cache - vendor
          keys:
            - vendor-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
      - run:
          name: Generate assets file
          command: go generate
      - run:
          name: Go packages install
          command: dep ensure
      - save_cache:
          name: Saving cache - vendor
          key: vendor-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"
      - run:
          name: Test
          command: go test github.com/h3poteto/hanazawabot/kanachan

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Check docker version
          command: docker version
      - run:
          name: Docker build
          command: docker build -t $AWS_ECR_REPOSITORY:latest .
      - run:
          name: Docker push
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker push $AWS_ECR_REPOSITORY:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
